import random

bible_quotes = [
    "For I know the plans I have for you, declares the Lord… — Jeremiah 29:11",
    "I can do all things through Christ who strengthens me. — Philippians 4:13",
    "The Lord is my shepherd; I shall not want. — Psalm 23:1",
    "Trust in the Lord with all your heart… — Proverbs 3:5-6",
    "Be strong and courageous… — Joshua 1:9",
    "Come to me, all you who are weary… — Matthew 11:28-30",
    "But those who hope in the Lord will renew their strength… — Isaiah 40:31",
    "The Lord will fight for you; you need only to be still. — Exodus 14:14",
    "Cast all your anxiety on Him because He cares for you. — 1 Peter 5:7",
    "Peace I leave with you; my peace I give you… — John 14:27",
    "Therefore do not worry about tomorrow… — Matthew 6:34",
    "Do not be anxious about anything… — Philippians 4:6-7",
    "Even though I walk through the valley… — Psalm 23:4",
    "So we fix our eyes not on what is seen… — 2 Corinthians 4:18",
    "The name of the Lord is a strong tower… — Proverbs 18:10",
    "God is our refuge and strength… — Psalm 46:1",
    "The Lord is near to the brokenhearted… — Psalm 34:18",
    "My flesh and my heart may fail… — Psalm 73:26",
    "He gives strength to the weary… — Isaiah 40:29",
    "The joy of the Lord is your strength. — Nehemiah 8:10",
    "When I am afraid, I put my trust in you. — Psalm 56:3",
    "But the fruit of the Spirit is love, joy, peace… — Galatians 5:22-23",
    "You are the light of the world… — Matthew 5:14-16",
    "Let all that you do be done in love. — 1 Corinthians 16:14",
    "Create in me a clean heart, O God… — Psalm 51:10",
    "Delight yourself in the Lord… — Psalm 37:4",
    "Be still, and know that I am God… — Psalm 46:10",
    "A cheerful heart is good medicine… — Proverbs 17:22",
    "In all your ways acknowledge him… — Proverbs 3:6",
    "The Lord is my light and my salvation… — Psalm 27:1",
    "Blessed is the one who perseveres under trial… — James 1:12",
    "You will keep in perfect peace… — Isaiah 26:3",
    "Give thanks to the Lord, for he is good… — Psalm 107:1",
    "The Lord your God is with you… — Zephaniah 3:17",
    "I sought the Lord, and he answered me… — Psalm 34:4",
    "And we know that in all things God works… — Romans 8:28",
    "No weapon formed against you shall prosper… — Isaiah 54:17",
    "The Lord is good, a refuge in times of trouble… — Nahum 1:7",
    "Be kind and compassionate to one another… — Ephesians 4:32",
    "Love is patient, love is kind… — 1 Corinthians 13:4-7",
    "This is the day that the Lord has made… — Psalm 118:24",
    "For the Spirit God gave us does not make us timid… — 2 Timothy 1:7",
    "Let your light shine before others… — Matthew 5:16",
    "Let everything that has breath praise the Lord. — Psalm 150:6",
    "For we live by faith, not by sight. — 2 Corinthians 5:7",
    "I will never leave you nor forsake you. — Hebrews 13:5",
    "Therefore encourage one another… — 1 Thessalonians 5:11",
    "I have loved you with an everlasting love… — Jeremiah 31:3",
    "As for me and my house, we will serve the Lord. — Joshua 24:15",
    "Do not be conformed to this world… — Romans 12:2",
    "Draw near to God and He will draw near to you. — James 4:8",
    "Let us not grow weary in doing good… — Galatians 6:9",
    "My grace is sufficient for you… — 2 Corinthians 12:9",
    "He who began a good work in you… — Philippians 1:6",
    "I am the way, the truth, and the life… — John 14:6",
    "The Lord is my strength and my song… — Psalm 118:14",
    "Do everything without grumbling… — Philippians 2:14-15",
    "The righteous cry out, and the Lord hears them… — Psalm 34:17",
    "And the peace of God… will guard your hearts… — Philippians 4:7",
    "Your word is a lamp for my feet… — Psalm 119:105",
    "I will praise you, Lord, with all my heart… — Psalm 138:1",
    "Let your gentleness be evident to all… — Philippians 4:5",
    "How great is the love the Father has lavished on us… — 1 John 3:1",
    "The Lord is gracious and righteous… — Psalm 116:5",
    "I am fearfully and wonderfully made… — Psalm 139:14",
    "If God is for us, who can be against us? — Romans 8:31",
    "Set your minds on things above… — Colossians 3:2",
    "Let the peace of Christ rule in your hearts… — Colossians 3:15",
    "Taste and see that the Lord is good… — Psalm 34:8",
    "We love because he first loved us. — 1 John 4:19",
    "He has made everything beautiful in its time… — Ecclesiastes 3:11",
    "Blessed are the peacemakers… — Matthew 5:9",
    "The heavens declare the glory of God… — Psalm 19:1",
    "Now faith is the substance of things hoped for… — Hebrews 11:1",
    "Trust in him at all times, you people… — Psalm 62:8",
    "Above all else, guard your heart… — Proverbs 4:23",
    "As iron sharpens iron… — Proverbs 27:17",
    "And my God will meet all your needs… — Philippians 4:19",
    "Therefore, if anyone is in Christ… — 2 Corinthians 5:17",
    "Let us hold unswervingly to the hope we profess… — Hebrews 10:23",
    "Surely your goodness and love will follow me… — Psalm 23:6",
    "Be devoted to one another in love… — Romans 12:10",
    "Humble yourselves before the Lord… — James 4:10",
    "Make every effort to keep the unity of the Spirit… — Ephesians 4:3",
    "He who dwells in the shelter of the Most High… — Psalm 91:1",
    "A friend loves at all times… — Proverbs 17:17",
    "Let us come before him with thanksgiving… — Psalm 95:2",
    "Teach us to number our days… — Psalm 90:12",
    "Carry each other’s burdens… — Galatians 6:2",
    "Be merciful, just as your Father is merciful. — Luke 6:36",
    "For everyone who asks receives… — Matthew 7:8",
    "You are altogether beautiful… — Song of Songs 4:7",
    "Your love has given me great joy… — Philemon 1:7",
    "The Lord is close to all who call on Him… — Psalm 145:18",
    "Open my eyes that I may see… — Psalm 119:18",
    "He will wipe every tear from their eyes… — Revelation 21:4",
    "I will give thanks to you, Lord, with all my heart… — Psalm 9:1",
    "Jesus Christ is the same yesterday and today and forever. — Hebrews 13:8",
    "Blessed are those who hunger and thirst for righteousness… — Matthew 5:6",
    "The Lord is compassionate and gracious… — Psalm 103:8",
    "Be strong in the Lord and in his mighty power. — Ephesians 6:10",
    "For the Lord gives wisdom… — Proverbs 2:6",
    "Call to me and I will answer you… — Jeremiah 33:3",
    "The Lord makes firm the steps of the one who delights in him… — Psalm 37:23"
]

def get_random_quote():
    return random.choice(bible_quotes)
